### ISSUE TITLE
Homepage - Resolution Checking: banner is not responsive

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#27] opened 2016-07-05 01:29 UTC
![image](https://cloud.githubusercontent.com/assets/17717843/16571677/f41a6bf0-4292-11e6-9299-656f6ce421ae.png)

**Comment by kraisitb** [comment] 2016-07-12 05:19
I've rechecked this and the banner is properly responsive (the screenshot also look fine though).

Could you please provide more details on this if the issue is still there?

**Comment by dremensayson** [comment] 2016-07-13 08:46
image is cut during resizing the page, image should retain it aspect ratio/size the entire resolution

**Comment by kraisitb** [comment] 2016-07-14 09:06
I use this project as an example: http://linesent.stage.titanweb.com.au/

Image cropping is use in viewport 1000px or larger in order to prevent an issue of banner image with different ratio i.e. square and rectangle.

The banner image would then be responsive in viewport lower than 1000px.

**Comment by dremensayson** [comment] 2016-07-15 02:48
Please refer to this website for fullly responsive banner. 
http://qsmfabrication.stage.titanweb.com.au/

**Comment by kraisitb** [comment] 2016-07-26 04:44
Should be fully responsive now for both banner image and banner content.

Note - the banner content font size is now dynamic based on the view port size, of which would not be the same size as in the mock but would be very close when viewing in a browser around 1300px.

**Comment by kraisitb** [comment] 2016-07-26 09:05
Should be fixed now as part of issue #117

**Comment by dremensayson** [comment] 2016-07-27 05:37
image is cropped in certain resolution from 993px to desktop view

**Comment by kraisitb** [comment] 2016-07-27 08:05
The banner image would not resize around 1000px - 1700px and then would be responsive again if the screen is larger.

This is in order to maintain enough space for the banner content.

**Comment by dremensayson** [comment] 2016-07-27 09:16
Can you please follow the responsive implementation of this sample site: http://qsmfabrication.stage.titanweb.com.au/

**Closed** 2016-07-28 01:25 UTC
Labels: bug, fixed
